# Generated by Django 6.0.3 on 2026-05-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteennear', '0004_add_approved_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='menu',
        ),
    ]
