# Generated by Django 6.0.4 on 2026-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteennear', '0008_apiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
